FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG VITE_API_URL=/api/v1
ARG VITE_API_BASE_URL=/api/v1

ENV VITE_API_URL=${VITE_API_URL} \
    VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build

FROM node:20-alpine AS preview

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY package.json package-lock.json ./
COPY vite.config.ts ./

RUN npm ci && npm cache clean --force

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]